'use client'
import { motion } from 'framer-motion'
import { MapPin, Phone, CalendarDays, Utensils, Sparkles } from 'lucide-react'
const fade={initial:{opacity:0,y:30},whileInView:{opacity:1,y:0},viewport:{once:true},transition:{duration:.75}}
export default function Home(){return <main className="min-h-screen bg-ink text-cream">
<nav className="fixed top-0 left-0 right-0 z-50 px-6 py-5 flex justify-between items-center bg-ink/70 backdrop-blur-xl border-b border-white/10"><a className="text-xl font-semibold tracking-[.18em]" href="#top">미각담다</a><div className="hidden md:flex gap-8 text-sm text-cream/70"><a href="#story">이야기</a><a href="#course">코스</a><a href="#space">공간</a><a href="#reserve">예약</a></div></nav>
<section id="top" className="relative min-h-screen flex items-center justify-center overflow-hidden"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_20%,rgba(184,155,94,.28),transparent_38%),linear-gradient(180deg,rgba(17,16,14,.2),#11100e)]"/><div className="absolute inset-0 opacity-20 bg-[url('https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=1800&auto=format&fit=crop')] bg-cover bg-center"/><motion.div initial={{opacity:0,y:50}} animate={{opacity:1,y:0}} transition={{duration:1}} className="relative z-10 text-center px-6"><p className="text-gold tracking-[.5em] text-sm mb-6">KOREAN DINING</p><h1 className="text-6xl md:text-8xl font-semibold tracking-[-.06em] mb-8">미각담다</h1><p className="text-2xl md:text-4xl leading-snug font-light">계절을 담고<br/>마음을 담다</p><a href="#reserve" className="inline-flex mt-12 px-8 py-4 rounded-full border border-gold text-gold hover:bg-gold hover:text-ink transition">예약 문의하기</a></motion.div></section>
<section id="story" className="px-6 py-28 max-w-6xl mx-auto grid md:grid-cols-2 gap-16 items-center"><motion.div {...fade}><p className="text-gold mb-4 tracking-[.3em]">BRAND STORY</p><h2 className="text-4xl md:text-5xl font-semibold leading-tight">전통의 맛을<br/>현대의 감각으로</h2></motion.div><motion.p {...fade} className="text-lg leading-9 text-cream/70">미각담다는 제철 식재료와 한식의 깊은 정서를 바탕으로, 오늘의 고객이 편안하게 즐길 수 있는 현대적 코스 요리를 제안합니다. 과하지 않게, 그러나 또렷하게 기억되는 한 끼를 만듭니다.</motion.p></section>
<section id="course" className="px-6 py-28 bg-cream text-ink"><div className="max-w-6xl mx-auto"><motion.p {...fade} className="text-gold mb-4 tracking-[.3em]">COURSE</motion.p><motion.h2 {...fade} className="text-4xl md:text-5xl font-semibold mb-12">계절 코스</motion.h2><div className="grid md:grid-cols-3 gap-6">{['Lunch Course','Dinner Course','Seasonal Special'].map((x,i)=><motion.div key={x} {...fade} className="rounded-3xl p-8 bg-white shadow-sm"><Utensils className="mb-8 text-gold"/><h3 className="text-2xl font-semibold mb-4">{x}</h3><p className="text-black/60 leading-7">제철 재료의 흐름에 맞춰 구성되는 미각담다의 코스입니다. 메뉴와 가격은 운영 상황에 따라 업데이트됩니다.</p></motion.div>)}</div></div></section>
<section id="space" className="px-6 py-28 max-w-6xl mx-auto"><motion.p {...fade} className="text-gold mb-4 tracking-[.3em]">SPACE</motion.p><motion.h2 {...fade} className="text-4xl md:text-5xl font-semibold mb-10">상견례, 비즈니스, 가족 모임을 위한 공간</motion.h2><div className="grid md:grid-cols-2 gap-6"><div className="glass rounded-3xl p-8"><Sparkles className="text-gold mb-6"/><h3 className="text-2xl font-semibold mb-3">프라이빗 룸</h3><p className="text-cream/65 leading-7">중요한 식사 자리를 조용하고 품격 있게 준비합니다.</p></div><div className="glass rounded-3xl p-8"><CalendarDays className="text-gold mb-6"/><h3 className="text-2xl font-semibold mb-3">예약 중심 운영</h3><p className="text-cream/65 leading-7">고객의 목적에 맞춰 코스와 좌석을 세심하게 안내합니다.</p></div></div></section>
<section id="reserve" className="px-6 py-28 bg-[#171512]"><div className="max-w-5xl mx-auto text-center"><motion.h2 {...fade} className="text-4xl md:text-6xl font-semibold mb-8">예약 및 문의</motion.h2><motion.p {...fade} className="text-cream/70 mb-10">미각담다의 공식 예약 채널과 위치 정보는 오픈 전 최종 세팅 후 연결됩니다.</motion.p><div className="flex flex-col md:flex-row gap-4 justify-center"><a className="px-8 py-4 rounded-full bg-gold text-ink font-semibold" href="tel:000-0000-0000"><Phone className="inline mr-2" size={18}/>전화 문의</a><a className="px-8 py-4 rounded-full border border-white/20" href="#"><MapPin className="inline mr-2" size={18}/>오시는 길</a></div></div></section>
<footer className="px-6 py-12 text-center text-cream/40">© Migakdamda. All rights reserved.</footer>
</main>}
